### ISSUE TITLE
[improvement]:  Enable / Disable root SSH access

### ISSUE THREAD

**Issue by kapilgupta01** [FreePBX/issue-tracker#117]
### FreePBX Version

FreePBX 17

### Improvement Description

Debian by default root ssh should be disabled.

In order to enable the support vpn we should also need to temporary enable the root ssh , hence we need option in UI to enable/disable the root ssh under sysadmin->support option. 

Also, give warning in the dashboard if the root ssh is enabled in the system.

**Comment by LightningManGTS** [comment]
Is there any intentions then on force creation of a username and password for a  user with root permissions through the ui? Securing the root user through freepbx is a good idea however 9/10 people going forward will be running this in a container of some kind and not a normal Debian install. Under an LXC or Docker by default there is no inline setup feature for creating new users. In the future less Linux savvy users will likely be setting up freepbx as docker containers so there should be some way to make a new user account that specifically should be used for ssh access through the ui. (Or even as a nice to have in case someone who can only access terminal through ssh toggles on the root ssh block and then is stuck with no access to create a separate user)

**Comment by kapilgupta01** [comment]
We have "ssh_keys" package which we installed whenever customer needs help from our support team. Here idea is to enable the root ssh (no password, access only with ssh keys) temporary and then disable it once the issue gets resolved so no need to create the new user.

**Comment by LightningManGTS** [comment]
> Here idea is to enable the root ssh (no password, access only with ssh keys) temporary and then disable it once the issue gets resolved so no need to create the new user.

Right sorry, I should of probably separated out my thought process here. My concern is that your effectively messing with the root user when somebody may already be using the root user normally for managing their container. So if they install the support keys then uninstall it, they end up losing ssh access to the container without really knowing why. 

Which is why I'm thinking if your going that route, either create a separate admin user for support or have the user make a separate admin at install/as a warning message and then automatically disable SSH for the true root user.

**Comment by ramarajan222** [comment]
Added support SSH user on the latest sysadmin version 17.0.1.82.
![image](https://github.com/FreePBX/issue-tracker/assets/25248291/5a7cb387-43c3-4ce5-b46e-b98eab6cb388)
