### ISSUE TITLE
[bug]:  PHP out-of-memory error in GUI after rebooting the system

### ISSUE THREAD

**Issue by ramarajan222** [FreePBX/issue-tracker#292]
### FreePBX Version

FreePBX 17

### Issue Description

Whoops \ Exception \ ErrorException (E_ERROR)
Allowed memory size of 536870912 bytes exhausted (tried to allocate 1281717103 bytes)

### Operating Environment

FreePBX V17

### Relevant log output

```shell
if(extension_loaded(‘ionCube Loader’)){die(‘The file ‘.FILE." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()==‘cli’)) ?‘ionCube’:’ionCube’)." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?“:\n\nhttps://get-loader.ioncube.com\n\nFor”:’ get-loader.ioncube.com and for’)." an instructional video please see".($cli?“:\n\nHome - PHP Encoder, protection, installer and performance tools from ionCube”:’ http://ioncu.be/LV ').“\n\n”);exit(199);
```

**Comment by kapilgupta01** [comment]
root cause - apache2 process was trying to start at the same time of freepbx and as freepbx process took more memory so apache2 didnt get enough memory to start properly hence on low memory vm/hardware we have noticed this issue.
Added fix in new sng install script to start the apache2 after freepbx process.

**Comment by MangNPB** [comment]
i just did a fresh install today: oct 23 2023 and this issue is still happening. multiple tries and errors with increasing php memories to changing timezone. none was solution. changing the allow ram size only cause long shutdown restart. i view your script in freepbx.service where apache2 was after mariadb after but it's not working for me. the only way to get apache2 to start is to call the restart command.

update right after i wrote the comment and still fiddling around. i pull after.apache2.service below the first call for network service and it seem to works. this means freepbx takes much longer to load than anticipated. is there a function to do a sleep 10 seconds or can i put after.apache2.service below both network calls?
