### ISSUE TITLE
[bug]: Advanced Recovery does not backup digital faxes even with Fax Pro

### ISSUE THREAD

**Issue by blazestudios97** [FreePBX/issue-tracker#304]
### FreePBX Version

FreePBX 16

### Issue Description

This issue most like impacts all versions of Advanced Recovery as this was found on a v16 system.

Advanced Recovery, despite backing up Fax and Fax Pro modules, does not include any backups of /var/spool/asterisk/fax which means that neither the primary or secondary server never keep any generated faxes when doing backups or restore/syncs. Advanced Recovery should be backing up all of /var/spool/asterisk because dynamically created items are being stored there.

Just found a location that deployed Advanced Recovery and their primary server had HDD failures. They followed the basic setup documents and worked under them impression the faxes were being backed up because their modules were being backed up and they also have Fax Pro.

Now they have recovered but lost all of their faxes which they apparently need.

### Operating Environment

SNG7

**Comment by kapilgupta01** [comment]
Hi @blazestudios97 

For Freepbx 17 , we recently added this improvement which allows the user to choose the fax data. (option text might be different as this might be old screenshot) 

![image](https://github.com/FreePBX/issue-tracker/assets/131970355/65f8439f-bebc-4a03-9c85-16d947edbe61)

**Comment by blazestudios97** [comment]
This needs to be back ported into v16. Not everyone running v16 is going to spin up new servers and jump to v17 immediately. So this is still a bug in v16 and needs to be addressed.

**Comment by girishmani1992** [comment]
Hi @blazestudios97 ,

The reported is fixed with faxpro v16.0.14 & v17.0.1.18, now in advanced recovery >  Configurations > primary Server Configurations, by default fax directory i.e _/var/spool/asterisk/fax_ is added in custom files section. While configuring, ensure faxpro is selected(By default all modules are selected in the list) and save the config. During sync, all fax files will restored to secondary pbx also. 

Custom files
![image](https://github.com/user-attachments/assets/71cb87eb-f7a2-4220-8ea9-e35cc5d78f16)


Module list in adv_recovery UI
![image](https://github.com/user-attachments/assets/096d5b2a-10c2-4d8f-868a-e53004b30e4e)


Thanks
